# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientConnection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ClientConnection.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  #create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x43lientConnection.proto\"\xa3\x01\n\rServerMessage\x12\x1f\n\ntrainOrder\x18\x01 \x01(\x0b\x32\x0b.TrainOrder\x12\x1d\n\tevalOrder\x18\x02 \x01(\x0b\x32\n.EvalOrder\x12)\n\x0f\x64isconnectOrder\x18\x03 \x01(\x0b\x32\x10.DisconnectOrder\x12\'\n\x0esetParamsOrder\x18\x04 \x01(\x0b\x32\x0f.SetParamsOrder\"\x8a\x01\n\rClientMessage\x12%\n\rtrainResponse\x18\x01 \x01(\x0b\x32\x0e.TrainResponse\x12#\n\x0c\x65valResponse\x18\x02 \x01(\x0b\x32\r.EvalResponse\x12-\n\x11setParamsResponse\x18\x03 \x01(\x0b\x32\x12.SetParamsResponse\"9\n\nTrainOrder\x12\x17\n\x0fmodelParameters\x18\x01 \x01(\x0c\x12\x12\n\nconfigDict\x18\x02 \x01(\x0c\">\n\rTrainResponse\x12\x17\n\x0fmodelParameters\x18\x01 \x01(\x0c\x12\x14\n\x0cresponseDict\x18\x02 \x01(\x0c\"8\n\tEvalOrder\x12\x17\n\x0fmodelParameters\x18\x01 \x01(\x0c\x12\x12\n\nconfigDict\x18\x02 \x01(\x0c\"$\n\x0c\x45valResponse\x12\x14\n\x0cresponseDict\x18\x01 \x01(\x0c\")\n\x0eSetParamsOrder\x12\x17\n\x0fmodelParameters\x18\x01 \x01(\x0c\"\x13\n\x11SetParamsResponse\"9\n\x0f\x44isconnectOrder\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x15\n\rreconnectTime\x18\x02 \x01(\x05\x32\x41\n\x10\x43lientConnection\x12-\n\x07\x43onnect\x12\x0e.ClientMessage\x1a\x0e.ServerMessage(\x01\x30\x01\x62\x06proto3'
)




_SERVERMESSAGE = _descriptor.Descriptor(
  name='ServerMessage',
  full_name='ServerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  #create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='trainOrder', full_name='ServerMessage.trainOrder', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='evalOrder', full_name='ServerMessage.evalOrder', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disconnectOrder', full_name='ServerMessage.disconnectOrder', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='setParamsOrder', full_name='ServerMessage.setParamsOrder', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=190,
)


_CLIENTMESSAGE = _descriptor.Descriptor(
  name='ClientMessage',
  full_name='ClientMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  #create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='trainResponse', full_name='ClientMessage.trainResponse', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='evalResponse', full_name='ClientMessage.evalResponse', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='setParamsResponse', full_name='ClientMessage.setParamsResponse', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=331,
)


_TRAINORDER = _descriptor.Descriptor(
  name='TrainOrder',
  full_name='TrainOrder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  #create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='modelParameters', full_name='TrainOrder.modelParameters', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='configDict', full_name='TrainOrder.configDict', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=390,
)


_TRAINRESPONSE = _descriptor.Descriptor(
  name='TrainResponse',
  full_name='TrainResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  #create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='modelParameters', full_name='TrainResponse.modelParameters', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='responseDict', full_name='TrainResponse.responseDict', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=454,
)


_EVALORDER = _descriptor.Descriptor(
  name='EvalOrder',
  full_name='EvalOrder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  #create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='modelParameters', full_name='EvalOrder.modelParameters', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='configDict', full_name='EvalOrder.configDict', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=456,
  serialized_end=512,
)


_EVALRESPONSE = _descriptor.Descriptor(
  name='EvalResponse',
  full_name='EvalResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  #create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseDict', full_name='EvalResponse.responseDict', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=514,
  serialized_end=550,
)


_SETPARAMSORDER = _descriptor.Descriptor(
  name='SetParamsOrder',
  full_name='SetParamsOrder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  #create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='modelParameters', full_name='SetParamsOrder.modelParameters', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=552,
  serialized_end=593,
)


_SETPARAMSRESPONSE = _descriptor.Descriptor(
  name='SetParamsResponse',
  full_name='SetParamsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  #create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=595,
  serialized_end=614,
)


_DISCONNECTORDER = _descriptor.Descriptor(
  name='DisconnectOrder',
  full_name='DisconnectOrder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  #create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='DisconnectOrder.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reconnectTime', full_name='DisconnectOrder.reconnectTime', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=616,
  serialized_end=673,
)

_SERVERMESSAGE.fields_by_name['trainOrder'].message_type = _TRAINORDER
_SERVERMESSAGE.fields_by_name['evalOrder'].message_type = _EVALORDER
_SERVERMESSAGE.fields_by_name['disconnectOrder'].message_type = _DISCONNECTORDER
_SERVERMESSAGE.fields_by_name['setParamsOrder'].message_type = _SETPARAMSORDER
_CLIENTMESSAGE.fields_by_name['trainResponse'].message_type = _TRAINRESPONSE
_CLIENTMESSAGE.fields_by_name['evalResponse'].message_type = _EVALRESPONSE
_CLIENTMESSAGE.fields_by_name['setParamsResponse'].message_type = _SETPARAMSRESPONSE
DESCRIPTOR.message_types_by_name['ServerMessage'] = _SERVERMESSAGE
DESCRIPTOR.message_types_by_name['ClientMessage'] = _CLIENTMESSAGE
DESCRIPTOR.message_types_by_name['TrainOrder'] = _TRAINORDER
DESCRIPTOR.message_types_by_name['TrainResponse'] = _TRAINRESPONSE
DESCRIPTOR.message_types_by_name['EvalOrder'] = _EVALORDER
DESCRIPTOR.message_types_by_name['EvalResponse'] = _EVALRESPONSE
DESCRIPTOR.message_types_by_name['SetParamsOrder'] = _SETPARAMSORDER
DESCRIPTOR.message_types_by_name['SetParamsResponse'] = _SETPARAMSRESPONSE
DESCRIPTOR.message_types_by_name['DisconnectOrder'] = _DISCONNECTORDER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServerMessage = _reflection.GeneratedProtocolMessageType('ServerMessage', (_message.Message,), {
  'DESCRIPTOR' : _SERVERMESSAGE,
  '__module__' : 'ClientConnection_pb2'
  # @@protoc_insertion_point(class_scope:ServerMessage)
  })
_sym_db.RegisterMessage(ServerMessage)

ClientMessage = _reflection.GeneratedProtocolMessageType('ClientMessage', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTMESSAGE,
  '__module__' : 'ClientConnection_pb2'
  # @@protoc_insertion_point(class_scope:ClientMessage)
  })
_sym_db.RegisterMessage(ClientMessage)

TrainOrder = _reflection.GeneratedProtocolMessageType('TrainOrder', (_message.Message,), {
  'DESCRIPTOR' : _TRAINORDER,
  '__module__' : 'ClientConnection_pb2'
  # @@protoc_insertion_point(class_scope:TrainOrder)
  })
_sym_db.RegisterMessage(TrainOrder)

TrainResponse = _reflection.GeneratedProtocolMessageType('TrainResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRAINRESPONSE,
  '__module__' : 'ClientConnection_pb2'
  # @@protoc_insertion_point(class_scope:TrainResponse)
  })
_sym_db.RegisterMessage(TrainResponse)

EvalOrder = _reflection.GeneratedProtocolMessageType('EvalOrder', (_message.Message,), {
  'DESCRIPTOR' : _EVALORDER,
  '__module__' : 'ClientConnection_pb2'
  # @@protoc_insertion_point(class_scope:EvalOrder)
  })
_sym_db.RegisterMessage(EvalOrder)

EvalResponse = _reflection.GeneratedProtocolMessageType('EvalResponse', (_message.Message,), {
  'DESCRIPTOR' : _EVALRESPONSE,
  '__module__' : 'ClientConnection_pb2'
  # @@protoc_insertion_point(class_scope:EvalResponse)
  })
_sym_db.RegisterMessage(EvalResponse)

SetParamsOrder = _reflection.GeneratedProtocolMessageType('SetParamsOrder', (_message.Message,), {
  'DESCRIPTOR' : _SETPARAMSORDER,
  '__module__' : 'ClientConnection_pb2'
  # @@protoc_insertion_point(class_scope:SetParamsOrder)
  })
_sym_db.RegisterMessage(SetParamsOrder)

SetParamsResponse = _reflection.GeneratedProtocolMessageType('SetParamsResponse', (
  _message.Message,),{
  'DESCRIPTOR' : _SETPARAMSRESPONSE,
  '__module__' : 'ClientConnection_pb2'
  # @@protoc_insertion_point(class_scope:SetParamsResponse)
  })
_sym_db.RegisterMessage(SetParamsResponse)

DisconnectOrder = _reflection.GeneratedProtocolMessageType('DisconnectOrder', (_message.Message,), {
  'DESCRIPTOR' : _DISCONNECTORDER,
  '__module__' : 'ClientConnection_pb2'
  # @@protoc_insertion_point(class_scope:DisconnectOrder)
  })
_sym_db.RegisterMessage(DisconnectOrder)



_CLIENTCONNECTION = _descriptor.ServiceDescriptor(
  name='ClientConnection',
  full_name='ClientConnection',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  #create_key=_descriptor._internal_create_key,
  serialized_start=675,
  serialized_end=740,
  methods=[
  _descriptor.MethodDescriptor(
    name='Connect',
    full_name='ClientConnection.Connect',
    index=0,
    containing_service=None,
    input_type=_CLIENTMESSAGE,
    output_type=_SERVERMESSAGE,
    serialized_options=None,
    #create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLIENTCONNECTION)

DESCRIPTOR.services_by_name['ClientConnection'] = _CLIENTCONNECTION

# @@protoc_insertion_point(module_scope)
